name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '1 2 * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.IHYZRHNY_TOKEN }}
          owner: MatsuriDayo
          base: main
          head: main
